#pragma once

#define KAC_SERVICE_PROC_NAME "OpenKAC_SVProc"
#define KAC_SERVICE_NAME "OpenKAC_Service"
#define KAC_SERVICE_DISPLAY_NAME "OpenKAC"
#define KAC_UNKOWN 0x0f
#define KAC_OPENSERVICE_FAIL 0x0f
#define KAC_SCMANGER_FAIL 0x0e
#define KAC_CREATESERVICE_FAIL 0x0d